# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- data
- build
- test

update_academic_tree:
  stage: data
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  tags:
    - hugo
  script :
    - mkdir -p ./data/bachelor
    - PGPASSWORD=$GAPS_DB_PASSWORD psql -q -t -A -h $GAPS_DB_HOST -U $GAPS_DB_USERNAME -d $GAPS_DB_NAME -f $BACHELOR_DATA_SQL > ./prebuild/data/bachelor.json
    #- PGPASSWORD=$GAPS_DB_PASSWORD psql -q -t -A -h $GAPS_DB_HOST -U $GAPS_DB_USERNAME -d $GAPS_DB_NAME -f $MASTER_DATA_SQL > ./prebuild/data/master.json
    - git config user.email "$GAPS_USER_EMAIL"
    - git config user.name "$GAPS_USER_NAME"
    - echo ${CI_PROJECT_PATH}
    - echo ${CI_SERVER_URL}
    - git remote rm origin && git remote add origin "https://oauth2:$PAT@$GAPS_CI_LOCATION/${CI_PROJECT_PATH}.git"
    - if output=$(git status --porcelain) && [ -z "$output" ]; then exit 0; fi
    - git add ./prebuild/data/bachelor.json
    #- git add ./prebuild/data/master.json
    - git commit -m "New data set from scheduled pipeline"
    - git push origin HEAD:main -o ci.skip

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  tags:
    - hugo
  script:
    - npm install
    - hugo

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
